services:
  app:
    build: .
    networks:
      - dokploy-network
    restart: unless-stopped

networks:
  default:
    external: true
    name: dokploy-network
  dokploy-network:
    external: true
