export interface RaidInventoryItem {
  className: string
  id: string
  name: string
  note: string
  power: number
  risk: number
  scarcity: number
  slot: RaidItemSlot
  stability: number
}

export type RaidItemSlot = 'armor' | 'relic' | 'supply' | 'tool' | 'weapon'

export const RAID_INVENTORY: RaidInventoryItem[] = [
  {
    className: 'Arc',
    id: 'ion-lance',
    name: 'Ion Lance Mk II',
    note: 'High breach output, unstable after long boss phases.',
    power: 89,
    risk: 24,
    scarcity: 71,
    slot: 'weapon',
    stability: 58,
  },
  {
    className: 'Kinetic',
    id: 'coil-shotgun',
    name: 'Coil Shotgun',
    note: 'Reliable close-range clear for cramped vault corridors.',
    power: 76,
    risk: 13,
    scarcity: 42,
    slot: 'weapon',
    stability: 82,
  },
  {
    className: 'Thermal',
    id: 'ember-repeater',
    name: 'Ember Repeater',
    note: 'Sustained pressure with strong armor melt.',
    power: 81,
    risk: 18,
    scarcity: 55,
    slot: 'weapon',
    stability: 73,
  },
  {
    className: 'Composite',
    id: 'mantle-rig',
    name: 'Mantle Rig',
    note: 'Absorbs burst damage but slows extraction windows.',
    power: 64,
    risk: 12,
    scarcity: 47,
    slot: 'armor',
    stability: 91,
  },
  {
    className: 'Reactive',
    id: 'aegis-frame',
    name: 'Aegis Frame',
    note: 'Best survival score for elite rooms and trap chains.',
    power: 70,
    risk: 16,
    scarcity: 66,
    slot: 'armor',
    stability: 86,
  },
  {
    className: 'Light',
    id: 'phase-vest',
    name: 'Phase Vest',
    note: 'Mobility armor for speed clears with fragile integrity.',
    power: 58,
    risk: 20,
    scarcity: 59,
    slot: 'armor',
    stability: 63,
  },
  {
    className: 'Scanner',
    id: 'echo-spike',
    name: 'Echo Spike',
    note: 'Maps hidden loot rooms and reduces ambush variance.',
    power: 53,
    risk: 8,
    scarcity: 61,
    slot: 'tool',
    stability: 88,
  },
  {
    className: 'Breaker',
    id: 'door-shear',
    name: 'Door Shear',
    note: 'Forces sealed cache rooms at the cost of alert pressure.',
    power: 68,
    risk: 19,
    scarcity: 49,
    slot: 'tool',
    stability: 74,
  },
  {
    className: 'Drone',
    id: 'specter-miner',
    name: 'Specter Miner',
    note: 'Autonomously retrieves loot while the kit holds threat.',
    power: 72,
    risk: 21,
    scarcity: 78,
    slot: 'tool',
    stability: 69,
  },
  {
    className: 'Ancient',
    id: 'sol-cipher',
    name: 'Sol Cipher',
    note: 'Unlocks provenance gates and rare receipt modifiers.',
    power: 77,
    risk: 22,
    scarcity: 90,
    slot: 'relic',
    stability: 64,
  },
  {
    className: 'Void',
    id: 'null-prism',
    name: 'Null Prism',
    note: 'Cancels one failure state but increases anomaly exposure.',
    power: 83,
    risk: 27,
    scarcity: 88,
    slot: 'relic',
    stability: 57,
  },
  {
    className: 'Guild',
    id: 'oath-token',
    name: 'Oath Token',
    note: 'Adds access rights for coordinated squad vaults.',
    power: 61,
    risk: 9,
    scarcity: 74,
    slot: 'relic',
    stability: 84,
  },
  {
    className: 'Medical',
    id: 'stasis-patch',
    name: 'Stasis Patch',
    note: 'Stabilizes long runs and protects the receipt payout.',
    power: 44,
    risk: 5,
    scarcity: 38,
    slot: 'supply',
    stability: 95,
  },
  {
    className: 'Charge',
    id: 'overcell-pack',
    name: 'Overcell Pack',
    note: 'Boosts weapon output during the final cache breach.',
    power: 67,
    risk: 15,
    scarcity: 52,
    slot: 'supply',
    stability: 79,
  },
  {
    className: 'Signal',
    id: 'rally-beacon',
    name: 'Rally Beacon',
    note: 'Improves extraction odds for wallet-bound access runs.',
    power: 56,
    risk: 10,
    scarcity: 45,
    slot: 'supply',
    stability: 87,
  },
]

export const RAID_SLOTS: RaidItemSlot[] = ['weapon', 'armor', 'tool', 'relic', 'supply']
